"""
Orchestrate the SQL cleaning pipeline.

    python src/run_pipeline.py

Runs sql/00→03 in order against a local DuckDB database, exports:
  - data/clean/fact_claims.parquet        (analysis-ready fact table)
  - data/clean/claims_quarantine.csv      (rejected rows + reasons)
  - reports/audit_tables.md               (all audit metrics, regenerated each run)

The pipeline exits non-zero if any acceptance test fails — quality gates are
enforced, not just reported.
"""

import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "sql"
DB_PATH = ROOT / "data" / "claims.duckdb"

SQL_FILES = ["00_load_raw.sql", "01_profiling.sql", "02_validation.sql", "03_cleaning.sql"]

AUDIT_TABLES = [
    ("audit.column_profile", "Column profile (completeness / cardinality)"),
    ("audit.date_format_census", "Date format census — date_filled"),
    ("audit.state_value_census", "State value census (raw encodings)"),
    ("audit.gender_value_census", "Gender value census (raw encodings)"),
    ("audit.price_profile", "Unit price distribution by therapeutic class"),
    ("audit.duplicate_profile", "Duplicate profile"),
    ("audit.violation_summary", "Validation rule summary"),
    ("audit.reconciliation", "Row reconciliation (raw = clean + quarantine + dupes)"),
    ("audit.acceptance_tests", "Post-clean acceptance tests"),
]


def main() -> int:
    con = duckdb.connect(str(DB_PATH))
    con.execute(f"SET file_search_path='{ROOT}'")

    for fname in SQL_FILES:
        sql = (SQL_DIR / fname).read_text()
        print(f"→ running {fname}")
        con.execute(sql)

    # Exports ---------------------------------------------------------------
    clean_dir = ROOT / "data" / "clean"
    clean_dir.mkdir(parents=True, exist_ok=True)
    con.execute(f"COPY clean.fact_claims TO '{clean_dir / 'fact_claims.parquet'}' (FORMAT PARQUET)")
    con.execute(f"COPY clean.claims_quarantine TO '{clean_dir / 'claims_quarantine.csv'}' (HEADER)")

    # Audit report ------------------------------------------------------------
    (ROOT / "reports").mkdir(exist_ok=True)
    lines = ["# Pipeline Audit Tables", "", "_Auto-generated by `src/run_pipeline.py`._", ""]
    for table, title in AUDIT_TABLES:
        df = con.execute(f"SELECT * FROM {table}").fetchdf()
        lines += [f"## {title}", "", df.to_markdown(index=False), ""]
    (ROOT / "reports" / "audit_tables.md").write_text("\n".join(lines))

    # Quality gate ------------------------------------------------------------
    failures = con.execute(
        "SELECT test, failures FROM audit.acceptance_tests WHERE failures > 0"
    ).fetchall()

    recon = con.execute("SELECT * FROM audit.reconciliation").fetchone()
    print(f"\nraw={recon[0]:,}  clean={recon[1]:,}  quarantined={recon[2]:,}  dupes_removed={recon[3]:,}")

    if failures:
        print("\n❌ ACCEPTANCE TESTS FAILED:")
        for test, n in failures:
            print(f"   {test}: {n} failing rows")
        return 1

    print("✅ all acceptance tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
